FROM python:3.9.7-slim-bullseye

# Image descriptions
LABEL maintainer="Fernando Zepeda"
LABEL version="0.1"
LABEL description = "Scaffolded Python Project"

RUN pip3 install --upgrade pip && \

WORKDIR /app

# COPY requirements.txt requirements.txt

# RUN pip install -r requirements.txt

# COPY . .

# CMD [ "python3", "./entrypoint.py" ]
